version: '3'

services:
  mysql:
    container_name: sickseek.local.db
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "friends"
      POSTGRES_PASSWORD: "friends"
      POSTGRES_DB: "sickseek"
    ports:
      - "5432:5432"
