version: '3'

services:
  mysql:
    container_name: sickseek.local.db
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "friends"
      POSTGRES_PASSWORD: "friends"
      POSTGRES_DB: "sickseek"
    ports:
      - "5432:5432"

  redis:
    image: redis:7.0-alpine
    container_name: sickseek.local.redis
    command: /bin/sh -c "redis-server --requirepass friends"
    ports:
      - "6379:6379"